name: "17 - 1 - Custom Actions - Composite"
env:
  working-directory: "17-custom-actions/react-app"
on:
  workflow_dispatch:
    inputs:
      target-env:
        type: choice
        options:
          - dev
          - prod
run-name: "17 - 1 - Custom Actions - Composite | env - ${{ inputs.target-env }}"
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ env.working-directory }}
    steps:
      - name: "Checkout"
        uses: "actions/checkout@v4"
      - name: "Setup Node and NPM dependencies"
        id: setup-deps
        uses: ./.github/actions/composite-cache-deps
        with:
          working-dir: ${{ env.working-directory }}
          node-version: "20.x"
          target-env: ${{ inputs.target-env }}
      - name: "Print setup deps output"
        run: 'echo "Installed dependencies: ${{ steps.setup-deps.outputs.installed-deps }}"'
      - name: "Test"
        run: npm run test
      - name: "Build"
        run: npm run build
