name: "17 - 2 - Custom Actions - JS"
permissions:
  contents: write
  pull-requests: write
on:
  workflow_dispatch:
    inputs:
      base-branch:
        type: string
        default: "main"
      target-branch:
        type: string
        default: "update-dependencies"
      working-directory:
        type: string
        default: "17-custom-actions/react-app"
      debug:
        type: boolean
        required: false
        default: false
run-name: "17 - 2 - Custom Actions - JS - Base: ${{ inputs.base-branch }} - Target: ${{ inputs.target-branch }} - Dir: ${{ inputs.working-directory }}"
jobs:
  dependency-update:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: "actions/checkout@v4"
      - name: "Check for dependency updates"
        id: update-deps
        uses: "./.github/actions/js-dependency-update"
        with:
          base-branch: ${{ inputs.base-branch }}
          target-branch: ${{ inputs.target-branch }}
          working-directory: ${{ inputs.working-directory }}
          debug: ${{ inputs.debug }}
          gh-token: ${{ secrets.GITHUB_TOKEN }}
      - name: "Print custom action output"
        run: 'echo "Updates available: ${{ steps.update-deps.outputs.updates-available }}'
