name: "17 - 3 - Custom Actions - Docker"
on:
  workflow_dispatch:
    inputs:
      url:
        type: choice
        required: false
        options:
          - "https://www.google.com"
          - "https://www.idontexist.not"
          - "not-a-url"
        default: "https://www.google.com"
      max_trials:
        required: false
        default: "10"
        description: "Maximum trials until action fails"
      delay:
        required: false
        default: "5"
        description: "Delay in seconds between trials"
jobs:
  ping-url:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: "actions/checkout@v4"
      - name: "Ping URL"
        uses: "./.github/actions/docker-ping-url"
        with:
          url: ${{ inputs.url }}
          max_trials: ${{ inputs.max_trials }}
          delay: ${{ inputs.delay }}
