name: "18 - 3 - Reusable Workflows"
on: workflow_dispatch
jobs:
  deploy:
    uses: "./.github/workflows/18-1-reusable-workflow.yaml"
    with:
      target-directory: "dummy-dir"
  e2e-tests:
    needs: deploy
    uses: devtobi/github-actions-course-example-e2e/.github/workflows/e2e.yaml@main
    secrets:
      access-token: ${{ secrets.GH_TOKEN }}
